#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<EOF >&2
Usage:
  $0 [--root ROOT] --case CASE --tag BASE_TAG [extra args for test_tpac.py]
  $0 ROOT CASE BASE_TAG [extra args for test_tpac.py]

What it does:
  - Find all YAML configs generated by wo.py under:
      ROOT/runs/wo/CASE/BASE_TAG/configs/
  - For each config:
      exp_tag = basename(config .yaml)
      ckpt    = ROOT/results/temp_results/CASE/exp_tag/weight/final_reco.pth
  - Run:
      python test_tpac.py --case CASE --tag exp_tag --ckpt ckpt --cfg config ...
      bash test.sh --case C1 --tag 1205 --device cuda:0 --pts 4096 --vis_indices 0,1,2,3,4,5 --phys_max_items -1

Examples:
  $0 --case ICA_norm --tag 1205 --device cuda:0 --pts 4096
  $0 /mnt/e/public/yzeng/codespace/yzeng/6yuan_task/task2_Rotate/Rotate ICA_norm 1205 --device cuda:0 --pts 4096
  $0 --case ICA_norm --tag 1205_all --device cuda:0 --pts 16384 --force_alpha 0.9
  $0 --case ICA_norm --tag 1205 --device cuda:0 --pts 4096 --vis_indices 2,3,4


Notes:
  - "BASE_TAG" is the tag you passed to wo.sh/wo.py (e.g., 1205 or 1205_all)
  - This script does NOT iterate multiple pth per experiment.
EOF
}

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# default root layout following your wo.sh style
DEFAULT_ROOT="$SCRIPT_DIR/Rotate"

ROOT_DIR=""
CASE=""
BASE_TAG=""
EXTRA_ARGS=()

# parse args (兼容：--case/--tag 形式 + 位置参数形式)
while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      [[ $# -ge 2 ]] || { echo "Error: --root expects a value" >&2; usage; exit 1; }
      ROOT_DIR="$2"
      shift 2
      ;;
    --case)
      [[ $# -ge 2 ]] || { echo "Error: --case expects a value" >&2; usage; exit 1; }
      CASE="$2"
      shift 2
      ;;
    --tag)
      [[ $# -ge 2 ]] || { echo "Error: --tag expects a value" >&2; usage; exit 1; }
      BASE_TAG="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    --)
      shift
      while [[ $# -gt 0 ]]; do
        EXTRA_ARGS+=("$1")
        shift
      done
      ;;
    *)
      # positional fallback: ROOT CASE TAG ...
      if [[ -z "$ROOT_DIR" && -d "$1" ]]; then
        ROOT_DIR="$1"
      elif [[ -z "$CASE" ]]; then
        CASE="$1"
      elif [[ -z "$BASE_TAG" ]]; then
        BASE_TAG="$1"
      else
        EXTRA_ARGS+=("$1")
      fi
      shift
      ;;
  esac
done

# fill defaults
if [[ -z "$ROOT_DIR" ]]; then
  ROOT_DIR="$DEFAULT_ROOT"
fi

if [[ -z "$CASE" || -z "$BASE_TAG" ]]; then
  echo "Error: missing --case or --tag." >&2
  usage
  exit 1
fi

ROOT_DIR=$(cd "$ROOT_DIR" && pwd)

TEST_SCRIPT="$ROOT_DIR/test_tpac.py"
CFG_DIR="$ROOT_DIR/runs/wo/$CASE/$BASE_TAG/configs"

if [[ ! -f "$TEST_SCRIPT" ]]; then
  echo "[ERR] test_tpac.py not found at: $TEST_SCRIPT" >&2
  exit 1
fi

if [[ ! -d "$CFG_DIR" ]]; then
  echo "[ERR] Config dir not found (did you run wo.py?): $CFG_DIR" >&2
  exit 1
fi

shopt -s nullglob

# 优先匹配你 wo.py 的命名习惯：{BASE_TAG}_*.yaml
CFG_FILES=("$CFG_DIR/${BASE_TAG}_*.yaml")

# 若命名不完全一致，fallback 到全量 yaml
if [[ ${#CFG_FILES[@]} -eq 0 ]]; then
  CFG_FILES=("$CFG_DIR/*.yaml")
fi

if [[ ${#CFG_FILES[@]} -eq 0 ]]; then
  echo "[ERR] No yaml configs found in: $CFG_DIR" >&2
  exit 1
fi

echo "[INFO] ROOT=$ROOT_DIR"
echo "[INFO] CASE=$CASE"
echo "[INFO] BASE_TAG=$BASE_TAG"
echo "[INFO] Found ${#CFG_FILES[@]} configs."

# 按文件名排序，保证顺序和 wo 的 order 更一致
IFS=$'\n' CFG_FILES=($(printf "%s\n" "${CFG_FILES[@]}" | sort))
unset IFS

for cfg in "${CFG_FILES[@]}"; do
  exp_tag=$(basename "$cfg" .yaml)
  ckpt="$ROOT_DIR/results/temp_results/$CASE/$exp_tag/weight/final_reco.pth"

  if [[ ! -f "$ckpt" ]]; then
    echo "[SKIP] missing ckpt for $exp_tag"
    echo "       expected: $ckpt"
    continue
  fi

  echo
  echo "=============================="
  echo "[TEST] $exp_tag"
  echo "  cfg : $cfg"
  echo "  ckpt: $ckpt"
  echo "=============================="

  python -u "$TEST_SCRIPT" \
    --root "$ROOT_DIR" \
    --case "$CASE" \
    --tag "$exp_tag" \
    --ckpt "$ckpt" \
    --cfg "$cfg" \
    "${EXTRA_ARGS[@]}"
done

echo
echo "[OK] All available experiments tested."
